version: '3'
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    volumes:
      - ".:/app"
    ports: 
      - '3000:3000'
    environment:
      - NODE_ENV=development
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
