version: "3"
services:
  api:
    container_name: docker-node-mongo
    restart: always
    build: ./backend
    volumes:
      - ./backend:/api
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - PORT=3000
    working_dir: /api
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: '--noauth'
  client:
    container_name: docker-react
    build: ./frontend
    volumes:
      - ./frontend:/client
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://localhost:3000
    working_dir: /client
    ports:
      - "8000:3000"
