version: "3"
services:
  api:
    container_name: docker-node-mongo
    restart: always
    build: ./backend
    volumes:
      - ./backend:/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    links:
      - mongo
      - client
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  client:
    container_name: docker-react
    build: ./frontend
    volumes:
      - ./frontend:/client
    environment: 
      - PORT=8000
      - REACT_APP_API_URL=http://localhost:3000
    ports:
      - "8000:8000"