version: '3'
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    volumes:
    - ".:/app"
    ports: 
      - '80:3000'
    environment:
      - NODE_ENV=development