version: '3'

services:
  rankmyapp:
    container_name: docker-node-mongo
    restart: always
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
